### ISSUE TITLE
bug issue

### ISSUE THREAD

**Issue by LoopyKirby** [leoleoasd/MLP-based-weighting#2]
I have a lot of problems when running this project. Is there any recently updated code?

**Comment by leoleoasd** [comment]
Hi,
No, there isn't. You can email me (i@yuxuan.lu) for your problems.

**Comment by LoopyKirby** [comment]
hi，
the url of this dataset is invalid. I tried to process the data.  and there are some adaptation problems and bugs I have sent you an email hoping to get help
